dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 24
  dataset_path: CellDataset:root=/nasdata2/dataset/dino/v2/CellDatasetCropped
  centering: sinkhorn_knopp
student:
  arch: vit_base
  patch_size: 14
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 200
  weight_decay_end: 0.2
  # base_lr: 2.0e-04  # learning rate for a batch size of 1024
  base_lr: 1.0e-02 # learning rate for a batch size of 64
  warmup_epochs: 10
  layerwise_decay: 1.0
crops:
  local_color_jit: false
  global_crops_scale:
  - 0.6
  - 1.0
  global_crops_size: 224
  local_crops_size: 140
  local_crops_number: 4
  local_crops_scale:
  - 1.0
  - 1.0